version: '3.1'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: fixme
      POSTGRES_DB: entity
    ports:
      - 5432:5432
    labels:
      org.label-schema.group: "runtime"
#  zookeeper:
#    image: docker.io/bitnami/zookeeper:3.7
#    ports:
#      - "2181:2181"
#    volumes:
#      - "zookeeper_data:/bitnami"
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
#    labels:
#      org.label-schema.group: "runtime"
#  kafka:
#    image: docker.io/bitnami/kafka:3
#    ports:
#      - "9092:9092"
#    volumes:
#      - "kafka_data:/bitnami"
#    environment:
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#      - ALLOW_PLAINTEXT_LISTENER=yes
#    depends_on:
#      - zookeeper
#    labels:
#      org.label-schema.group: "runtime"
  promethous:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:latest
    depends_on:
      - promethous
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - 3000:3000
    labels:
      org.label-schema.group: "monitoring"

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local