version: '3.1'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: fixme
      POSTGRES_DB: entity
    ports:
      - 5432:5432
    labels:
      org.label-schema.group: "runtime"
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    labels:
      org.label-schema.group: "runtime"
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    labels:
      org.label-schema.group: "runtime"
  promethous:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./local/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    labels:
      org.label-schema.group: "monitoring"
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./local/grafana/data:/var/lib/grafana
      - ./local/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - 3000:3000
    labels:
      org.label-schema.group: "monitoring"